package com.genius.travel_genius.models;

public enum ActivityType {
    ADVENTURE, SIGHTSEEING, ROMANTIC, CULTURAL, SHOPPING, HISTORICAL, NIGHTLIFE, SPORTS, RELIGIOUS, ENTERTAINMENT, RELAXATION, GASTRONOMY, NATURE_WILDLIFE
}
